name: FTP Deploy Yii2 App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: 📦 Deploy Yii2 App to Shared Hosting
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v3

      - name: 📦 Deploy via FTP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          port: 21
          source: "./"
          target: "/htdocs/"
