name: Yii2 CI/CD - Deploy Only

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: ?? Deploy Yii2 App
    runs-on: ubuntu-latest

    steps:
      - name: ?? Checkout Code
        uses: actions/checkout@v3

      - name: ?? Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, intl, pdo, pdo_mysql
          ini-values: post_max_size=256M, upload_max_filesize=256M

      - name: ?? Install Composer Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: ?? Set Writable Permissions (Optional)
        run: |
          chmod -R 777 runtime
          chmod -R 777 web/assets

      - name: ?? Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASS }}
            port: 21
          script: |
            cd /var/www/html/yii2-app
            git pull origin main
            composer install --no-interaction --prefer-dist --optimize-autoloader
            php yii migrate --interactive=0
